name: Generate Headless Test

on:
  workflow_dispatch:
    inputs:
      requirement:
        description: "Requirement description"
        required: true
      background:
        description: "Primary background context (e.g., Talabat food mobile application)"
        required: true
        default: "Talabat food mobile application"
      additional-background:
        description: "Additional context (e.g., logged in user, pro subscribed user)"
        required: false
      squad:
        description: "Squad name (e.g., squad-auth)"
        required: true
      file-name:
        description: "Test file name (e.g., login-with-email)"
        required: false
      tag:
        description: "Priority tag (e.g., P0, P1)"
        required: false
      other-tags:
        description: "Other tags (e.g., smoke, login, regression)"
        required: false  

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install Python package
        run: pip install .

      - name: Generate healess test
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_BRANCH: ${{ github.ref_name }}
        run: |
          generate-headlesstest \
            --requirement "${{ github.event.inputs.requirement }}" \
            --squad "${{ github.event.inputs.squad }}" \
            --file-name "${{ github.event.inputs.file-name }}" \
            --tag "${{ github.event.inputs.tag }}" \
            --other-tags "${{ github.event.inputs.other-tags }}" \
            --additional-background "${{ github.event.inputs.additional-background }}"


      

