name: Generate Gherkin Test Cases

on:
  workflow_dispatch:
    inputs:
      requirement:
        description: "Requirement for test cases"
        required: true
      squad:
        description: "Squad name"
        required: true
      file_name:
        description: "Optional file name"
        required: false
      tag:
        description: "Priority tag (e.g. P0)"
        required: false
      other_tags:
        description: "Other tags (comma or space separated)"
        required: false
      additional_background:
        description: "Additional background (e.g. logged in user)"
        required: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install .

      - name: Generate Gherkin test cases
        run: |
          generate-tests \
            --requirement "${{ github.event.inputs.requirement }}" \
            --squad "${{ github.event.inputs.squad }}" \
            ${{
              github.event.inputs.file_name && 
              format('--file-name "{}"', github.event.inputs.file_name) || ''
            }} \
            ${{
              github.event.inputs.tag && 
              format('--tag "{}"', github.event.inputs.tag) || ''
            }} \
            ${{
              github.event.inputs.other_tags && 
              format('--other-tags "{}"', github.event.inputs.other_tags) || ''
            }} \
            ${{
              github.event.inputs.additional_background && 
              format('--additional-background "{}"', github.event.inputs.additional_background) || ''
            }}

      - name: Generate Headless Flutter tests
        run: |
          generate-headlesstest \
            --requirement "${{ github.event.inputs.requirement }}" \
            --squad "${{ github.event.inputs.squad }}" \
            ${{
              github.event.inputs.file_name && 
              format('--file-name "{}"', github.event.inputs.file_name) || ''
            }} \
            ${{
              github.event.inputs.tag && 
              format('--tag "{}"', github.event.inputs.tag) || ''
            }} \
            ${{
              github.event.inputs.other_tags && 
              format('--other-tags "{}"', github.event.inputs.other_tags) || ''
            }} \
            ${{
              github.event.inputs.additional_background && 
              format('--additional-background "{}"', github.event.inputs.additional_background) || ''
            }}

      - name: Commit and push new test files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add test-cases headless-test
          git commit -m "🔄 Auto-generated test cases and headless test code"
          git push
        continue-on-error: true
